INSERT INTO clientes(name, surname, email, create_at, foto) VALUES ('Manolito', 'Guey', 'manolito@gmail.com', '2019-07-17', '');
INSERT INTO clientes(name, surname, email, create_at, foto) VALUES ('Manolito', 'Guey', 'manolito@gmail.com', '2019-07-17', '');
INSERT INTO clientes(name, surname, email, create_at, foto) VALUES ('Manolito', 'Guey', 'manolito@gmail.com', '2019-07-17', '');
INSERT INTO clientes(name, surname, email, create_at, foto) VALUES ('Jose', 'Villegas', 'jmaa@gmail.com', '2019-07-19', '');
INSERT INTO clientes(name, surname, email, create_at, foto) VALUES ('Jose', 'Villegas', 'jmaa@gmail.com', '2019-07-19', '');
INSERT INTO clientes(name, surname, email, create_at, foto) VALUES ('Manolito', 'Guey', 'manolito@gmail.com', '2019-07-17', '');
INSERT INTO clientes(name, surname, email, create_at, foto) VALUES ('Jose', 'Villegas', 'jmaa@gmail.com', '2019-07-19', '');
INSERT INTO clientes(name, surname, email, create_at, foto) VALUES ('Manolito', 'Guey', 'manolito@gmail.com', '2019-07-17', '');
INSERT INTO clientes(name, surname, email, create_at, foto) VALUES ('Jose', 'Villegas', 'jmaa@gmail.com', '2019-07-19', '');
INSERT INTO clientes(name, surname, email, create_at, foto) VALUES ('Manolito', 'Guey', 'manolito@gmail.com', '2019-07-17', '');
INSERT INTO clientes(name, surname, email, create_at, foto) VALUES ('Jose', 'Villegas', 'jmaa@gmail.com', '2019-07-19', '');
INSERT INTO clientes(name, surname, email, create_at, foto) VALUES ('Manolito', 'Guey', 'manolito@gmail.com', '2019-07-17', '');
INSERT INTO clientes(name, surname, email, create_at, foto) VALUES ('Jose', 'Villegas', 'jmaa@gmail.com', '2019-07-19', '');
INSERT INTO clientes(name, surname, email, create_at, foto) VALUES ('Manolito', 'Guey', 'manolito@gmail.com', '2019-07-17', '');
INSERT INTO clientes(name, surname, email, create_at, foto) VALUES ('Jose', 'Villegas', 'jmaa@gmail.com', '2019-07-19', '');
INSERT INTO clientes(name, surname, email, create_at, foto) VALUES ('Manolito', 'Guey', 'manolito@gmail.com', '2019-07-17', '');
INSERT INTO clientes(name, surname, email, create_at, foto) VALUES ('Jose', 'Villegas', 'jmaa@gmail.com', '2019-07-19', '');
INSERT INTO clientes(name, surname, email, create_at, foto) VALUES ('Manolito', 'Guey', 'manolito@gmail.com', '2019-07-17', '');
INSERT INTO clientes(name, surname, email, create_at, foto) VALUES ('Jose', 'Villegas', 'jmaa@gmail.com', '2019-07-19', '');
INSERT INTO clientes(name, surname, email, create_at, foto) VALUES ('Manolito', 'Guey', 'manolito@gmail.com', '2019-07-17', '');
INSERT INTO clientes(name, surname, email, create_at, foto) VALUES ('Jose', 'Villegas', 'jmaa@gmail.com', '2019-07-19', '');
INSERT INTO clientes(name, surname, email, create_at, foto) VALUES ('Manolito', 'Guey', 'manolito@gmail.com', '2019-07-17', '');
INSERT INTO clientes(name, surname, email, create_at, foto) VALUES ('Jose', 'Villegas', 'jmaa@gmail.com', '2019-07-19', '');
INSERT INTO clientes(name, surname, email, create_at, foto) VALUES ('Manolito', 'Guey', 'manolito@gmail.com', '2019-07-17', '');
INSERT INTO clientes(name, surname, email, create_at, foto) VALUES ('Jose', 'Villegas', 'jmaa@gmail.com', '2019-07-19', '');
INSERT INTO clientes(name, surname, email, create_at, foto) VALUES ('Manolito', 'Guey', 'manolito@gmail.com', '2019-07-17', '');
INSERT INTO clientes(name, surname, email, create_at, foto) VALUES ('Jose', 'Villegas', 'jmaa@gmail.com', '2019-07-19', '');
INSERT INTO clientes(name, surname, email, create_at, foto) VALUES ('Manolito', 'Guey', 'manolito@gmail.com', '2019-07-17', '');
INSERT INTO clientes(name, surname, email, create_at, foto) VALUES ('Jose', 'Villegas', 'jmaa@gmail.com', '2019-07-19', '');
INSERT INTO clientes(name, surname, email, create_at, foto) VALUES ('Manolito', 'Guey', 'manolito@gmail.com', '2019-07-17', '');
INSERT INTO clientes(name, surname, email, create_at, foto) VALUES ('Jose', 'Villegas', 'jmaa@gmail.com', '2019-07-19', '');
INSERT INTO clientes(name, surname, email, create_at, foto) VALUES ('Manolito', 'Guey', 'manolito@gmail.com', '2019-07-17', '');

INSERT INTO products(name, price, create_at) VALUES ('Panasonic LCD 45', '3754', NOW());
INSERT INTO products(name, price, create_at) VALUES ('Sony Camara Digital pepino', '548', NOW());
INSERT INTO products(name, price, create_at) VALUES ('Asus PC guay', '2354', NOW());
INSERT INTO products(name, price, create_at) VALUES ('Disco duro SSD', '25', NOW());
INSERT INTO products(name, price, create_at) VALUES ('Raton Logitech bonito', '7744', NOW());
INSERT INTO products(name, price, create_at) VALUES ('Teclado Skiller', '65', NOW());

INSERT INTO facturas(description, observations, cliente_id, create_at) VALUES ('Facturas de oficina', null, 1, NOW());
INSERT INTO facturas_item(number, product_id, factura_id) VALUES (1, 1, 1);
INSERT INTO facturas_item(number, product_id, factura_id) VALUES (2, 2, 1);
INSERT INTO facturas_item(number, product_id, factura_id) VALUES (1, 4, 1);
INSERT INTO facturas_item(number, product_id, factura_id) VALUES (1, 3, 1);
